# Numpy

Numpy es el principal paquete de Python para opreaciones cientificas.

#### Intrucciones
* Se utilizara Python 3


## Importando Numpy

Sintaxis basica de import:
```
 "import" module ["as" name]
``` 

In [1]:
import numpy as np

## Ejemplos con Numpy

En Python contamos con multiples librerias muy populares para realizar opreciones numericas pero muchas funcionan solo con numeros reales como entrada, este es un problema en machine learning ya que la mayor parte del tiempo trabajamos con matrices y vectores, por lo que Numpy se convierte en una de las herramientas mas importantes

### Exponencial

Compararemos el paquete Math de Python con Numpy para demostrar la ventaja de Numpy al trabajar con vectores y matrices.

Exponencial ($e^x$) con el paquete Math

In [24]:
import math

math.exp(3)

20.085536923187668

Exponencial ($e^x$) con el paquete Numpy

[Documentacion oficial](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html)

In [27]:
np.exp(3)

20.085536923187668

Se obtuvo el mismo resultado pero el paquete Math casi no se utiliza para machine learning porque tiene la desventaja que no perminte realizar operaciones sobre vectores.

Si tenemos por ejemplo el vector ``` x = [ 1 , 1 , 2 , 3 , 5 ] ``` numpy aplica la funcion exponecnial a cada elemento del vector:

np.exp(x) = $(e^{x_1}, e^{x_2}, ..., e^{x_n})$


In [14]:
x = np.array([ 1 , 1 , 2 , 3 , 5 ])

np.exp(x)

array([  2.71828183,   2.71828183,   7.3890561 ,  20.08553692,
       148.4131591 ])

Incluso podemos realizar operaciones con data elemepnto del vector, por ejemplo ``` x + 3 ```

In [15]:
print (x + 3)

[4 4 5 6 8]


### Vectorizacion

In [28]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

#### Producto punto de dos vectores con Numpy

In [29]:
np.dot(x1,x2)

278

#### Multiplicacion por elementos

In [30]:
np.multiply(x1,x2)

array([81,  4, 10,  0,  0, 63, 10,  0,  0,  0, 81,  4, 25,  0,  0])

### Matrices

In [32]:
a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


In [37]:
# otra forma de definir matrices en np
b = np.matrix([[5, 1, 6], [2, 9, 0], [5, 4, 9]])

print(b)

[[5 1 6]
 [2 9 0]
 [5 4 9]]


#### Matrices Transpuestas

In [55]:
b = np.matrix([[5, 1, 6], [2, 9, 0], [5, 4, 9]])
print(b)
print("")

print("Matriz transpuesta:")
np.transpose(b)

[[5 1 6]
 [2 9 0]
 [5 4 9]]

Matriz transpuesta:


matrix([[5, 2, 5],
        [1, 9, 4],
        [6, 0, 9]])

#### Multiplicacion de matrices
[Documentacion oficial](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html)

In [40]:
a = [[1, 0], [0, 1]]
b = [1, 2]
np.matmul(a, b)

array([1, 2])

#### Multiplicion por elementos

[Documentacion oficial](https://docs.scipy.org/doc/numpy/reference/generated/numpy.multiply.html)

In [46]:
np.multiply(a, b)

array([[1, 0],
       [0, 2]])

In [43]:
## Multiplicamos la matriz a por un escalar
np.multiply(a, 4)

array([[4, 0],
       [0, 4]])

#### Producto punto entre matrices

In [38]:
a = np.matrix([[1, 0], [0, 1]])
b = np.matrix([[4, 1], [2, 2]])

np.dot(a, b)

matrix([[4, 1],
        [2, 2]])

### Operaciones de Matrices en Machine learning

Una aplicacion en machine learning con matrices y numpy es la normalizacion, consiste en cambiar x a $ \frac{x}{\| x\|} $ (dividir cada fila por su norm).

Ejemplo:

Si $$x =
\begin{bmatrix}
 0 & 3 & 4 \\ 
 2 & 6 & 4 \\ 
\end{bmatrix}\tag{3}$$ entonces $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}  
 5 \\ 
 8 \\ 
\end{bmatrix}\tag{4} $$y $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix} 
 0 & 3/5 & 4/5 \\ 
 2/8 & 6/8 & 4/8 \\
\end{bmatrix}\tag{5}$$

In [47]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])

x / np.linalg.norm(x,axis=1,keepdims=True)

array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])