### Vamos a hacer aprendizaje supervisado, especificamente clasificacion

Usaremos un dataset que contiene caracteristicas de flores como el ancho y largo de sus petalos y sepalos(estos son los features X)
Y por cada flor, tenemos a que especie pertenece(Y) de 3 posibles clases Setosa, Versicolour, y Virginica

Nuestro algoritmo sera capaz de identificar el tipo de nuevas flores, sin necesidad de crear una serie de reglas en la programacion ,si no que lo aprendera de el dataset de entrenamiento.

Nuestro algoritmo tomara este dataset, y aprendera a identificar flores en funcion del largo y ancho de sus petalos y sepalos 
sin que necesitemos especificarle reglas, el lo aprendera de los datos

<img src="iris_dataset.jpg">

In [21]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression 
from sklearn import metrics
import numpy as np

In [2]:
iris_data = datasets.load_iris()

In [3]:
X_train = iris_data.data
Y_train = iris_data.target

##### Columnas Sepal Length, Sepal Width, Petal Length , Petal Width.

In [4]:
X_train[0:15]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2]])

In [5]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
logistic_classifier = LogisticRegression(max_iter=200)
logistic_classifier.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=200, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
train_prediction = logistic_classifier.predict(X_train)

In [9]:
print("Classification report for classifier %s:\n%s\n"
      % (logistic_classifier, metrics.classification_report(Y_train, train_prediction)))

Classification report for classifier LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=200, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False):
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.98      0.90      0.94        50
          2       0.91      0.98      0.94        50

avg / total       0.96      0.96      0.96       150




In [10]:
for i in range(len(Y_train)):
    prediction = logistic_classifier.predict(X_train[i].reshape(1,-1))
    real = Y_train[i]
    print("Real:",real,"Prediction",prediction)
    

Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Prediction [0]
Real: 0 Pre

In [41]:
def export_model(model):
    print("Intercepts:",logistic_classifier.intercept_)
    print("Coefficients:",logistic_classifier.coef_)
    
    class1_params = [logistic_classifier.intercept_[0]]  + list(logistic_classifier.coef_[0])
    print("Class 1 params",class1_params)
    ## Ejercicio: encuentra los parametros para los otros 2 modelos y escribe el resultado en un archivo csv
    
export_model(logistic_classifier)

Intercepts: [ 0.26560617  1.08542374 -1.21471458]
Coefficients: [[ 0.41498833  1.46129739 -2.26214118 -1.0290951 ]
 [ 0.41663969 -1.60083319  0.57765763 -1.38553843]
 [-1.70752515 -1.53426834  2.47097168  2.55538211]]
Class 1 params [0.26560616797551728, 0.41498832829570065, 1.4612973885622274, -2.2621411772020728, -1.02909509924489]


In [38]:
[logistic_classifier.intercept_[0]]  + list(logistic_classifier.coef_[0])

[0.26560616797551728,
 0.41498832829570065,
 1.4612973885622274,
 -2.2621411772020728,
 -1.02909509924489]